### ISSUE TITLE
Move/add Rstudio to `r-workbench`

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/researchcloud-items#182]
Dawa: I think it's a great idea to add RStudio to the `r-workbench` playbook, on desktop workspaces. I think this could be very simply done by adding something like the following to the `roles:` section of the `r-workbench` playbook:

```yaml
roles:
  - fact_workspace_info
  - rstudio
    when: fact_desktop_workspace
```

...although there may be the complication that roles are executed before tasks, so we should make sure `rstudio` is included after r is installed. In that case, you might have to do:

```yaml
roles:
  - fact_workspace_info
  ...
 tasks:
     # R is installed here
    - name: Include ansible-r role
      when: fact_desktop_workspace
      include_role:
        role: rstudio
```
