### ISSUE TITLE
Check parameter handling in molecule tests

### ISSUE THREAD

**Issue by dometto** [UtrechtUniversity/researchcloud-items#56]
I noticed that a playbook that was passing the tests actually failed to deploy on Research Cloud due to the way that parameters seem to be handled: what was really a string value `'true'` on SRC was a boolean `true` in our molecule setup. This caused the parameters to be handled differently in the role (`security_updates`). I will research if we can get rid of this discrepancy, or else document that string values should be used for parameters in our tests.

**Comment by dometto** [comment]
I've investigated the way variables in SRC portal are passed on to ansible using https://github.com/dometto/src-vars-debug

Results (this is what ansible receives, input in SRC portal in the comment on each line):

```yaml
boolean: 'true' # true
boolean2: 'False' # False
json: '[{name:jammy,component:main,packages:/srv/aptly/pkgs,architectures:[amd64]}]\n[{name:focal,component:main,packages:/srv/aptly/pkgs,architectures:[amd64, arm64]}]' # multiline string becomes oneline string with explicit '\n' in it
stringwithdoublequotes: hello # "hello"
stringwithsinglequotes: hello # 'hello'
```

As you can see quotes are sanitized, while multiline strings become single line strings, and booleans become strings.
